// Code generated using std.sh; DO NOT EDIT.

// We will ignore that fact that some of packages
// were removed from stdlib.

package analyzer

var std = map[string]struct{}{
	// added in Go v1.2 in compare to v1.1 (docker image)
	"archive/tar":         struct{}{},
	"archive/zip":         struct{}{},
	"bufio":               struct{}{},
	"bytes":               struct{}{},
	"cmd/cgo":             struct{}{},
	"cmd/fix":             struct{}{},
	"cmd/go":              struct{}{},
	"cmd/gofmt":           struct{}{},
	"cmd/yacc":            struct{}{},
	"compress/bzip2":      struct{}{},
	"compress/flate":      struct{}{},
	"compress/gzip":       struct{}{},
	"compress/lzw":        struct{}{},
	"compress/zlib":       struct{}{},
	"container/heap":      struct{}{},
	"container/list":      struct{}{},
	"container/ring":      struct{}{},
	"crypto":              struct{}{},
	"crypto/aes":          struct{}{},
	"crypto/cipher":       struct{}{},
	"crypto/des":          struct{}{},
	"crypto/dsa":          struct{}{},
	"crypto/ecdsa":        struct{}{},
	"crypto/elliptic":     struct{}{},
	"crypto/hmac":         struct{}{},
	"crypto/md5":          struct{}{},
	"crypto/rand":         struct{}{},
	"crypto/rc4":          struct{}{},
	"crypto/rsa":          struct{}{},
	"crypto/sha1":         struct{}{},
	"crypto/sha256":       struct{}{},
	"crypto/sha512":       struct{}{},
	"crypto/subtle":       struct{}{},
	"crypto/tls":          struct{}{},
	"crypto/x509":         struct{}{},
	"crypto/x509/pkix":    struct{}{},
	"database/sql":        struct{}{},
	"database/sql/driver": struct{}{},
	"debug/dwarf":         struct{}{},
	"debug/elf":           struct{}{},
	"debug/gosym":         struct{}{},
	"debug/macho":         struct{}{},
	"debug/pe":            struct{}{},
	"encoding":            struct{}{},
	"encoding/ascii85":    struct{}{},
	"encoding/asn1":       struct{}{},
	"encoding/base32":     struct{}{},
	"encoding/base64":     struct{}{},
	"encoding/binary":     struct{}{},
	"encoding/csv":        struct{}{},
	"encoding/gob":        struct{}{},
	"encoding/hex":        struct{}{},
	"encoding/json":       struct{}{},
	"encoding/pem":        struct{}{},
	"encoding/xml":        struct{}{},
	"errors":              struct{}{},
	"expvar":              struct{}{},
	"flag":                struct{}{},
	"fmt":                 struct{}{},
	"go/ast":              struct{}{},
	"go/build":            struct{}{},
	"go/doc":              struct{}{},
	"go/format":           struct{}{},
	"go/parser":           struct{}{},
	"go/printer":          struct{}{},
	"go/scanner":          struct{}{},
	"go/token":            struct{}{},
	"hash":                struct{}{},
	"hash/adler32":        struct{}{},
	"hash/crc32":          struct{}{},
	"hash/crc64":          struct{}{},
	"hash/fnv":            struct{}{},
	"html":                struct{}{},
	"html/template":       struct{}{},
	"image":               struct{}{},
	"image/color":         struct{}{},
	"image/color/palette": struct{}{},
	"image/draw":          struct{}{},
	"image/gif":           struct{}{},
	"image/jpeg":          struct{}{},
	"image/png":           struct{}{},
	"index/suffixarray":   struct{}{},
	"io":                  struct{}{},
	"io/ioutil":           struct{}{},
	"log":                 struct{}{},
	"log/syslog":          struct{}{},
	"math":                struct{}{},
	"math/big":            struct{}{},
	"math/cmplx":          struct{}{},
	"math/rand":           struct{}{},
	"mime":                struct{}{},
	"mime/multipart":      struct{}{},
	"net":                 struct{}{},
	"net/http":            struct{}{},
	"net/http/cgi":        struct{}{},
	"net/http/cookiejar":  struct{}{},
	"net/http/fcgi":       struct{}{},
	"net/http/httptest":   struct{}{},
	"net/http/httputil":   struct{}{},
	"net/http/pprof":      struct{}{},
	"net/mail":            struct{}{},
	"net/rpc":             struct{}{},
	"net/rpc/jsonrpc":     struct{}{},
	"net/smtp":            struct{}{},
	"net/textproto":       struct{}{},
	"net/url":             struct{}{},
	"os":                  struct{}{},
	"os/exec":             struct{}{},
	"os/signal":           struct{}{},
	"os/user":             struct{}{},
	"path":                struct{}{},
	"path/filepath":       struct{}{},
	"reflect":             struct{}{},
	"regexp":              struct{}{},
	"regexp/syntax":       struct{}{},
	"runtime":             struct{}{},
	"runtime/cgo":         struct{}{},
	"runtime/debug":       struct{}{},
	"runtime/pprof":       struct{}{},
	"runtime/race":        struct{}{},
	"sort":                struct{}{},
	"strconv":             struct{}{},
	"strings":             struct{}{},
	"sync":                struct{}{},
	"sync/atomic":         struct{}{},
	"syscall":             struct{}{},
	"testing":             struct{}{},
	"testing/iotest":      struct{}{},
	"testing/quick":       struct{}{},
	"text/scanner":        struct{}{},
	"text/tabwriter":      struct{}{},
	"text/template":       struct{}{},
	"text/template/parse": struct{}{},
	"time":                struct{}{},
	"unicode":             struct{}{},
	"unicode/utf16":       struct{}{},
	"unicode/utf8":        struct{}{},
	"unsafe":              struct{}{},
	// added in Go v1.3 in compare to v1.2 (docker image)
	"cmd/addr2line":  struct{}{},
	"cmd/nm":         struct{}{},
	"cmd/objdump":    struct{}{},
	"cmd/pack":       struct{}{},
	"debug/plan9obj": struct{}{},
	// added in Go v1.4 in compare to v1.3 (docker image)
	"cmd/pprof": struct{}{},
	// added in Go v1.5 in compare to v1.4 (docker image)
	"go/constant":          struct{}{},
	"go/importer":          struct{}{},
	"go/types":             struct{}{},
	"mime/quotedprintable": struct{}{},
	"runtime/trace":        struct{}{},
	// added in Go v1.6 in compare to v1.5 (docker image)
	// added in Go v1.7 in compare to v1.6 (docker image)
	"context":            struct{}{},
	"net/http/httptrace": struct{}{},
	// added in Go v1.8 in compare to v1.7 (docker image)
	"plugin": struct{}{},
	// added in Go v1.9 in compare to v1.8 (docker image)
	"math/bits": struct{}{},
	// added in Go v1.10 in compare to v1.9 (docker image)
	// added in Go v1.11 in compare to v1.10 (docker image)
	// added in Go v1.12 in compare to v1.11 (docker image)
	// added in Go v1.13 in compare to v1.12 (docker image)
	"crypto/ed25519": struct{}{},
	// added in Go v1.14 in compare to v1.13 (docker image)
	"hash/maphash": struct{}{},
	// added in Go v1.15 in compare to v1.14 (docker image)
	"time/tzdata": struct{}{},
	// added in Go v1.16 in compare to v1.15 (docker image)
	"embed":               struct{}{},
	"go/build/constraint": struct{}{},
	"io/fs":               struct{}{},
	"runtime/metrics":     struct{}{},
	"testing/fstest":      struct{}{},
	// added in Go v1.17 in compare to v1.16 (docker image)
}
